## Deployment pack"
- hosts: localhost
  become: true
  tasks:
  - name: Deploying the docker-containers to the localhost
    docker_container:
      name: "docker_deploy"
      image: yuvayrj1/dockertest
      recreate: yes
      state: started
      restart: yes
      ports:
              - 8090:3000
      volumes:
        - "devcdn:/docker-node/cdn:rw"

