## Deployment pack"
- hosts: localhost
  become: true
  tasks:
  - name: Log into dockerhub registry | force re-auth
    docker_login:
      registry: yuvayrj1/dockertest

  - name: Pull an latest image from dockerhub.aximsoft.com registry
    docker_image:
      name: "{{LATEST_VER}}"

  - name: Deploying the docker-containers to the localhost
    docker_container:
      name: "docker_deploy"
      image: "{{LATEST_VER}}"
      recreate: yes
      state: started
      restart: yes
      ports:
              - 8090:3000
      volumes:
        - "devcdn:/docker-node/cdn:rw"

